/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_disni_util_NativeAffinity */

#ifndef _Included_com_ibm_disni_util_NativeAffinity
#define _Included_com_ibm_disni_util_NativeAffinity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_disni_util_NativeAffinity
 * Method:    _setAffinity
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_disni_util_NativeAffinity__1setAffinity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_disni_util_NativeAffinity
 * Method:    _getAffinity
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_disni_util_NativeAffinity__1getAffinity
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
